# Generated by Django 4.2.3 on 2023-07-10 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transcription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('last_modified', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('link', models.URLField(max_length=2000)),
                ('transcript', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
