# Generated by Django 4.2.3 on 2023-07-11 11:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("transcribe", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="transcription",
            name="language",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="transcription",
            name="title",
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
